
build:
  date: '@build.date@'

pringfox:
  documentation:
    swagger:
      use-model-v3: false

http-server:
  http:
    port: 8080

spa:
  default-file: /dist/index.html


spring:
  security:
    user:
      name: "ssafy"
      password: "ssafy"

  redis:
    host: j5a605.p.ssafy.io
    port: 8000
  profiles:
    include:
      - db

  oauth2:
    client:
      registration:
        kakao:
          authorization-grant-type: authorization_code
          client-id: 1e31c0b3e807829e950f0236c26efec6
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope:
            - profile
            - account_email
          client-authentication-method: POST
          client-name: Kakao

      provider:

        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: http://kapi.kakao.com/v2/user/me
          user-name-attribute: id


  data:
    web:
      pageable:
        one-indexed-parameters: true

  devtools:
    livereload:
      enabled: true

  jpa:
    show-sql : true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql : true
        format_sql : true
        use_sql_comment: true
  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false
    static-locations: classpath:/dist/

