spring:
  datasource:
    password: walk123
    username: www
    url: jdbc:mariadb://j5a605.p.ssafy.io:3306/www?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect


#spring:
#  datasource:
#    password: walk123
#    username: www
#    url: jdbc:mariadb://j5a605.p.ssafy.io:3306/www?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
#    driver-class-name: org.mariadb.jdbc.Driver
